'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace EditableDetails


	''' <summary>
	''' _Default class.
	''' </summary>
	''' <remarks>
	''' Auto-generated class.
	''' </remarks>
	Partial Public Class _Default

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' masterGrid control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected masterGrid As Global.DevExpress.Web.ASPxGridView.ASPxGridView

		''' <summary>
		''' SqlDataSourceCustomers control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected SqlDataSourceCustomers As Global.System.Web.UI.WebControls.SqlDataSource

		''' <summary>
		''' SqlDataSourceOrders control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected SqlDataSourceOrders As Global.System.Web.UI.WebControls.SqlDataSource
	End Class
End Namespace
